[package]
name = "symsorter"
version = "0.1.0"
authors = ["Sentry <hello@getsentry.com>"]
edition = "2018"

[dependencies]
structopt = "0.2.18"
clap = "2.33.0"
failure = "0.1.5"
walkdir = "2.2.8"
symbolic = { git = "https://github.com/getsentry/symbolic", rev = "cc2dc6992097b1d442ad25aa1b63e28bb637df72", features = ["debuginfo-serde"] }
console = "0.7.7"
zstd = "0.4.27"
itertools = "0.8.0"
zip = "0.5.2"
parking_lot = "0.9.0"
